# fly.toml app configuration file generated for web1-pdnssa on 2026-05-13T07:07:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web1-pdnssa'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
